create table client (
    id bigint generated by default as identity,
    adresse_facturation varchar(255) not null,
    adresse_livraison varchar(255) not null,
    nom varchar(255) not null,
    prenom varchar(255) not null,
    primary key (id)
);

create table facture (
    fk_client_id bigint not null,
    id bigint generated by default as identity,
    statut varchar(255) not null check (
        statut in (
            'CREATION',
            'ENVOYEE',
            'PAYEE'
        )
    ),
    primary key (id)
);

create table fichiers (
    fk_facture_id bigint not null,
    id bigint generated by default as identity,
    path varchar(255) not null,
    type_file varchar(255) not null,
    primary key (id)
);

create table fournisseur (
    id bigint generated by default as identity,
    adresse varchar(255) not null,
    nom_entreprise varchar(255) not null,
    primary key (id)
);

create table fournisseur_produit (
    prix_fournisseur numeric(19, 2) not null,
    stock_fournisseur integer not null,
    fk_fournisseur_id bigint not null,
    fk_produit_id bigint not null,
    primary key (
        fk_fournisseur_id,
        fk_produit_id
    )
);

create table produits (
    id bigint generated by default as identity,
    description varchar(255) not null,
    libelle varchar(255) not null,
    primary key (id)
);

create table produits_facture (
    prix_unitaire numeric(19, 2) not null,
    quantite integer,
    fk_facture_id bigint not null,
    fk_fournisseur_id bigint not null,
    fk_produit_id bigint not null,
    primary key (
        fk_facture_id,
        fk_fournisseur_id,
        fk_produit_id
    )
);

alter table if exists facture
add constraint FK192bycl1wqgqev5lns12i9b1t foreign key (fk_client_id) references client;

alter table if exists fichiers
add constraint FKmog0b94rsogkjhvtdd38ls0mv foreign key (fk_facture_id) references facture;

alter table if exists fournisseur_produit
add constraint FKqfy6rv6lab9fanv16nexq12hh foreign key (fk_fournisseur_id) references fournisseur;

alter table if exists fournisseur_produit
add constraint FKhy56gb1bm467etr55rpkdf9j1 foreign key (fk_produit_id) references produits;

alter table if exists produits_facture
add constraint FK2yvdr6mrmt6ba5as6cabh2mp0 foreign key (fk_facture_id) references facture;

alter table if exists produits_facture
add constraint FK4c3w2nennmaeymhj57vknx6dt foreign key (fk_fournisseur_id) references fournisseur;

alter table if exists produits_facture
add constraint FK69lhp4gserpx5u981gk8w6bu3 foreign key (fk_produit_id) references produits;

INSERT INTO
    client (
        nom,
        prenom,
        adresse_facturation,
        adresse_livraison
    )
VALUES (
        'Dupont',
        'Jean',
        '10 Rue de la Paix, 75002 Paris',
        '10 Rue de la Paix, 75002 Paris'
    );

INSERT INTO
    client (
        nom,
        prenom,
        adresse_facturation,
        adresse_livraison
    )
VALUES (
        'Martin',
        'Sophie',
        '25 Avenue des Champs-Élysées, 75008 Paris',
        '3 Quai de la Loire, 44000 Nantes'
    );

INSERT INTO
    client (
        nom,
        prenom,
        adresse_facturation,
        adresse_livraison
    )
VALUES (
        'Bernard',
        'Thomas',
        '8 Place Bellecour, 69002 Lyon',
        '8 Place Bellecour, 69002 Lyon'
    );

INSERT INTO
    produits (libelle, description)
VALUES (
        'Ecran 27 pouces',
        'Ecran idéal pour la bureautique'
    );

INSERT INTO
    produits (libelle, description)
VALUES ('Clavier', 'Clavier filaire');

INSERT INTO
    produits (libelle, description)
VALUES (
        'Souris Sans Fil',
        'Souris sans fil'
    );

INSERT INTO
    produits (libelle, description)
VALUES (
        'Casque Audio Bluetooth',
        'Casque avec 30h d autonomie'
    );

INSERT INTO
    fournisseur (nom_entreprise, adresse)
VALUES (
        'TechDistro Corp',
        '120 Boulevard Haussmann, 75008 Paris'
    );

INSERT INTO
    fournisseur (nom_entreprise, adresse)
VALUES (
        'Global Electronics',
        '45 Rue du Commerce, 69003 Lyon'
    );

INSERT INTO
    fournisseur_produit (
        fk_fournisseur_id,
        fk_produit_id,
        prix_fournisseur,
        stock_fournisseur
    )
VALUES (1, 1, 299.99, 50);

INSERT INTO
    fournisseur_produit (
        fk_fournisseur_id,
        fk_produit_id,
        prix_fournisseur,
        stock_fournisseur
    )
VALUES (1, 2, 79.50, 120);

INSERT INTO
    fournisseur_produit (
        fk_fournisseur_id,
        fk_produit_id,
        prix_fournisseur,
        stock_fournisseur
    )
VALUES (1, 3, 45.00, 200);

INSERT INTO
    fournisseur_produit (
        fk_fournisseur_id,
        fk_produit_id,
        prix_fournisseur,
        stock_fournisseur
    )
VALUES (2, 1, 280.00, 15);

INSERT INTO
    fournisseur_produit (
        fk_fournisseur_id,
        fk_produit_id,
        prix_fournisseur,
        stock_fournisseur
    )
VALUES (2, 4, 129.90, 80);

INSERT INTO facture (fk_client_id, statut) VALUES (1, 'PAYEE');

INSERT INTO facture (fk_client_id, statut) VALUES (1, 'ENVOYEE');

INSERT INTO facture (fk_client_id, statut) VALUES (2, 'CREATION');

INSERT INTO
    produits_facture (
        fk_facture_id,
        fk_produit_id,
        fk_fournisseur_id,
        quantite,
        prix_unitaire
    )
VALUES (1, 1, 1, 1, 300);

INSERT INTO
    produits_facture (
        fk_facture_id,
        fk_produit_id,
        fk_fournisseur_id,
        quantite,
        prix_unitaire
    )
VALUES (1, 3, 1, 1, 45);

INSERT INTO
    produits_facture (
        fk_facture_id,
        fk_produit_id,
        fk_fournisseur_id,
        quantite,
        prix_unitaire
    )
VALUES (2, 2, 1, 2, 80);

INSERT INTO
    produits_facture (
        fk_facture_id,
        fk_produit_id,
        fk_fournisseur_id,
        quantite,
        prix_unitaire
    )
VALUES (3, 4, 2, 1, 130);